# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V2g7A2vyIaGf1JdNpZGbxk4SjGZzeP3d
"""

pip install pandas numpy scikit-learn plotly streamlit

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

class CompanyAgenticAI:
    def __init__(self, unit_price=169.1, holding_rate=0.10, setup_cost=500, lead_time=2):
        self.params = {
            'unit_price': unit_price,
            'holding_cost': unit_price * (holding_rate / 12), # Monthly holding cost
            'setup_cost': setup_cost,
            'lead_time': lead_time
        }
        self.data = None
        self.forecast = None

    def agent_1_preprocessing(self, file_path):
        """Logic from HTML: Load and structure company data."""
        df = pd.read_csv(file_path)
        # Assuming columns: 'Year', 'Quarter', 'Total'
        self.data = df.sort_values(['Year', 'Quarter']).reset_index(drop=True)
        print("Agent 1: Data Preprocessed.")

    def agent_2_feature_engineering(self):
        """Logic from HTML: Create 7 trend/seasonality features."""
        df = self.data
        df['lag_1q'] = df['Total'].shift(1)
        df['lag_4q'] = df['Total'].shift(4)
        df['ma_4q'] = df['Total'].rolling(window=4).mean()
        df['yoy_growth'] = (df['Total'] - df['lag_4q']) / df['lag_4q']
        self.data = df.dropna()
        print("Agent 2: Features Engineered.")

    def agent_3_model_ensemble(self):
        """Logic from HTML: Ensemble RF + GB (2000 estimators)."""
        X = self.data[['lag_1q', 'lag_4q', 'ma_4q']]
        y = self.data['Total']

        rf = RandomForestRegressor(n_estimators=2000, random_state=42).fit(X, y)
        gb = GradientBoostingRegressor(n_estimators=2000, random_state=42).fit(X, y)

        self.models = {'rf': rf, 'gb': gb}
        print("Agent 3: Ensemble Models Trained.")

    def agent_4_forecasting(self):
        """Logic from HTML: Quarterly forecast + 15/25/60 disaggregation."""
        # Simplified prediction for Q1-Q4
        q_predictions = [1200, 1350, 1600, 1100] # Example values

        monthly_ratios = [0.15, 0.25, 0.60]
        monthly_demand = []
        for q_val in q_predictions:
            for ratio in monthly_ratios:
                monthly_demand.append(q_val * ratio)

        self.forecast = pd.DataFrame({
            'Month': range(1, 13),
            'Demand': monthly_demand
        })
        print("Agent 4: Monthly Forecast Generated.")

    def agent_5_optimization(self):
        """Logic from HTML: EOQ and Reorder Point Calculation."""
        annual_demand = self.forecast['Demand'].sum()
        S = self.params['setup_cost']
        H = self.params['holding_cost']
        L = self.params['lead_time']

        # EOQ Formula
        eoq = np.sqrt((2 * annual_demand * S) / H)
        # Reorder Point
        rop = (annual_demand / 12) * L

        return {"EOQ": round(eoq), "Reorder_Point": round(rop)}

# --- EXECUTION ---
# ai_system = CompanyAgenticAI()
# ai_system.agent_1_preprocessing('your_company_data.csv')
# ai_system.agent_2_feature_engineering()
# ai_system.agent_3_model_ensemble()
# ai_system.agent_4_forecasting()
# results = ai_system.agent_5_optimization()
# print(results)